# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KoreaTripRank' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KoreaTripRank

  pod 'Alamofire'
  pod 'SnapKit'
  target 'KoreaTripRankTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KoreaTripRankUITests' do
    # Pods for testing
  end

end
