# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'KoreaTripRank' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KoreaTripRank

  pod 'Alamofire'
  pod 'SnapKit'
  pod 'SwiftGen', '~> 6.6.0'
  target 'KoreaTripRankTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KoreaTripRankUITests' do
    # Pods for testing
  end

end
